[phases.setup]
nixPkgs = ['python310', 'ffmpeg', 'gcc']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r backend/requirements.txt'
]

[start]
cmd = 'cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT'
