[build]
builder = "NIXPACKS"
buildCommand = "python3 -m pip install -r backend/requirements.txt"

[deploy]
startCommand = "cd backend && python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.10"
