name: smart_assistant
description: Smart Personal Assistant - المساعد الشخصي الذكي
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Network
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Permissions
  permission_handler: ^11.3.0
  
  # Audio
  audioplayers: ^5.2.1
  just_audio: ^0.9.36
  record: ^5.0.4
  
  # Phone & Calls
  phone_state: ^1.0.3
  call_log: ^4.0.2
  flutter_phone_direct_caller: ^2.1.1
  
  # Contacts & WhatsApp
  contacts_service: ^0.6.3
  
  # AI APIs
  google_generative_ai: ^0.2.1
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.19.0
  timeago: ^3.6.0
  
  # Charts
  fl_chart: ^0.65.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
